local DefaultStats = {
	Health = 400,
	WalkSpeed = 18,
	JumpHeight = 7.2,
	-- Custom Stats
	RunSpeed = 28,

	-- Stamina = 100,
	--? Maybe add Stamina later

	--* Mining
	MiningSpeed = 1,
	MiningFortune = 1, -- Yields more items
	MiningLuck = 1, -- Higher chance for rare drops

	--* Lumberjacking

	LumberjackingSpeed = 1,
	LumberjackingFortune = 1,
	LumberjackingLuck = 1,

	--* Combat
	DashDuration = 0.25,
	DashCooldown = 2,
}
return DefaultStats
